[package]
name = "spider-volt"
version = "0.1.0"
edition = "2024"

[dependencies]
battery = "0.7.8"
clap = "4.5.57"
notify-rust = "4.11.7"
rodio = "0.21.1"
rstest = "0.26.1"
serde = "1.0.228"
toml = "0.9.11"
